//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_working_SoundDog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string ExtraInfo { get; set; }
        public Nullable<System.DateTime> DateReservationCreated { get; set; }
        public Nullable<bool> ReservationActive { get; set; }
        public Nullable<bool> ReservationChecked { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Room Room { get; set; }
        public virtual Time Time { get; set; }
    }
}
